version: '3'
services:
  mysql:
    build:
      context: mysql
    image: $GITHUB_USER/rs-mysql-db:$TAG
    cap_add:
      - NET_ADMIN
    networks:
      - robot-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  ratings:
    build:
      context: ratings
    image: $GITHUB_USER/rs-ratings:$TAG
    networks:
      - robot-shop
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - NEW_RELIC_APP_NAME=$SERVICE_NAME-$CLOUD_PROVIDER;$SERVICE_NAME
      - NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
      - NEW_RELIC_LABELS=datacenter:$CLOUD_PROVIDER;service:$SERVICE_NAME
networks:
  robot-shop:
